=== Cateatspython/warjournalsfromardennesduringwwi/mid_term.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT TEI (teiHeader, text)>
<!ELEMENT teiHeader (fileDesc)>
<!ELEMENT fileDesc (titleStmt, publicationStmt, sourceDesc)>
<!ELEMENT titleStmt (title+, author+)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT publicationStmt (publisher, date)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ATTLIST date when CDATA #REQUIRED>
<!ELEMENT sourceDesc (msDesc)>
<!ELEMENT msDesc (msIdentifier, msContents)>
<!ATTLIST msDesc xml:id CDATA #REQUIRED>
<!ELEMENT msIdentifier (settlement, repository, idno)>
<!ELEMENT settlement (#PCDATA)>
<!ELEMENT repository (#PCDATA)>
<!ELEMENT idno (#PCDATA)>
<!ELEMENT msContents (msItem)>
<!ELEMENT msItem (title, author)>
<!ELEMENT text (body)>
<!ELEMENT body (div+)>
<!ELEMENT div (p+)>
<!ATTLIST div type CDATA #REQUIRED>
<!ATTLIST div n CDATA #REQUIRED>
<!ELEMENT p (#PCDATA | date | time | persName | placeName | formula | figure | del | note | event)*>
<!ELEMENT time (#PCDATA)>
<!ATTLIST time when CDATA #REQUIRED>
<!ELEMENT persName (#PCDATA)>
<!ATTLIST persName xml:id CDATA #REQUIRED>
<!ELEMENT placeName (#PCDATA)>
<!ATTLIST placeName xml:id CDATA #REQUIRED>
<!ELEMENT formula (#PCDATA)>
<!ELEMENT figure (#PCDATA)>
<!ELEMENT del (#PCDATA)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT event (#PCDATA)>
<!ATTLIST event xml:id CDATA #REQUIRED>

=== Cateatspython/warjournalsfromardennesduringwwi/mid_term.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml"
	schematypens="http://purl.oclc.org/dsdl/schematron"?>
<!DOCTYPE TEI SYSTEM "mid_term.dtd">
<TEI xmlns="http://www.tei-c.org/ns/1.0">
   <teiHeader>
      <fileDesc>
         <titleStmt>
            <title>file title</title>
            <author>encoder name</author>
         </titleStmt>
         <publicationStmt>
            <publisher>editor name</publisher>
            <date when="2024-10-26">26 octobre 2024</date>
         </publicationStmt>
         <sourceDesc>
            <msDesc xml:id="journal1">
               <msIdentifier>
                  <settlement>Charleville-Mézières</settlement>
                  <repository> Archives départements des Ardennes</repository>
                  <idno>classification mark</idno>
               </msIdentifier>
               <msContents>
                  <msItem>
                     <title>journal title</title>
                     <author>journal author</author>
                  </msItem>
               </msContents>
            </msDesc>
         </sourceDesc>
      </fileDesc>
   </teiHeader>
   <text>
      <body>
         <!-- division for each journal day -->
         <div type="day" n="1">
            <!-- text -->
            <p>
               <!-- date (and time if specified)  -->
               <date when="1914-10-04">4 octobre</date>
               <time when="01:45:00">01:45</time>
            </p>
            <p>
               <!-- name of a person mentioned -->
               <persName xml:id="personA">Jacqueline</persName>
               <!-- name of a place mentioned -->
               <placeName xml:id="place1"> Sorendal</placeName>
               <!-- calculations -->
               <formula/>
               <!-- drawing -->
               <figure/>
               <del/>
               <!-- writing in the margins -->
               <note place="margin"/>
               <!-- name of an event mentioned -->
               <eventName xml:id="event1"/>
            </p>
            <!-- page change -->
            <pb n="2"/>
         </div>
         <div type="day" n="2">
            <p>
               <date when="1914-10-05">5 octobre</date>
               <time when="05:35:00">05:35</time>
            </p>
            <p>
               <!-- text -->
            </p>
         </div>
      </body>
   </text>
</TEI>
